table 'Report measures (2)'
	lineageTag: a708f9eb-20d3-4f48-8a07-d708dd33d82a

	measure 'VS makers' = SUM(electric_vehicle_sales_by_makers[electric_vehicles_sold])
		formatString: 0
		lineageTag: 25892b0b-3840-4a97-94ef-888adc05ccac

	measure 'VS state' = SUM(electric_vehicle_sales_by_state[electric_vehicles_sold])
		formatString: 0
		lineageTag: d64ff84f-1ed0-43f9-b4bd-195b7dbff117

	measure 'Penetration rate %' = DIVIDE([VS state],SUM(electric_vehicle_sales_by_state[total_vehicles_sold]),0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 52dee45f-6dee-4070-8e5e-7544e18a8744

	partition 'Report measures (2)' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

